package com.example.autoestimator

object PriceData {
    val prices = mapOf(
        "door_min_dent" to Pair(4800, 2000),
        "door_mod_dent" to Pair(5000, 2500),
        "door_sev_dent" to Pair(6000, 3000),
        "f_bumper_min" to Pair(4800, 2000),
        "f_bumper_mod" to Pair(6000, 3000),
        "f_bumper_sev" to Pair(7000, 3500),
        "f_windshield" to Pair(18000, 15000),
        "fender_min" to Pair(6800, 3500),
        "fender_mod" to Pair(7500, 3500),
        "fender_sev" to Pair(9800, 6500),
        "headlight_min" to Pair(6500, 3000),
        "headlight_mod" to Pair(7000, 4000),
        "headlight_sev" to Pair(7000, 4500),
        "hood_min" to Pair(5500, 2500),
        "hood_mod" to Pair(6800, 3500),
        "hood_sev" to Pair(7000, 4500),
        "r_bumper_min" to Pair(8500, 6000),
        "r_bumper_mod" to Pair(15000, 12500),
        "r_bumper_sev" to Pair(28000, 21000),
        "r_windshield" to Pair(18000, 15000),
        "roof_min" to Pair(6800, 4000),
        "roof_mod" to Pair(7800, 5000),
        "roof_sev" to Pair(8500, -1),
        "runningboard" to Pair(4800, 3000),
        "side_window" to Pair(1800, 1100),
        "sidemirror" to Pair(3000, 2500),
        "tail_light_min" to Pair(4800, 3000),
        "tail_light_mod" to Pair(5800, 4000),
        "tail_light_sev" to Pair(6800, 4500),
        "trunk_min" to Pair(5500, 2500),
        "trunk_mod" to Pair(6800, 3500),
        "trunk_sev" to Pair(7000, 4500)
    )

    val labelNames = mapOf(
        "door_min_dent" to "Door (Minor Dent)",
        "door_mod_dent" to "Door (Moderate Dent)",
        "door_sev_dent" to "Door (Severe Dent)",
        "f_bumper_min" to "Front Bumper (Minor)",
        "f_bumper_mod" to "Front Bumper (Moderate)",
        "f_bumper_sev" to "Front Bumper (Severe)",
        "f_windshield" to "Front Windshield",
        "fender_min" to "Fender (Minor)",
        "fender_mod" to "Fender (Moderate)",
        "fender_sev" to "Fender (Severe)",
        "headlight_min" to "Headlight (Minor)",
        "headlight_mod" to "Headlight (Moderate)",
        "headlight_sev" to "Headlight (Severe)",
        "hood_min" to "Hood (Minor)",
        "hood_mod" to "Hood (Moderate)",
        "hood_sev" to "Hood (Severe)",
        "r_bumper_min" to "Rear Bumper (Minor)",
        "r_bumper_mod" to "Rear Bumper (Moderate)",
        "r_bumper_sev" to "Rear Bumper (Severe)",
        "r_windshield" to "Rear Windshield",
        "roof_min" to "Roof (Minor)",
        "roof_mod" to "Roof (Moderate)",
        "roof_sev" to "Roof (Severe)",
        "runningboard" to "Running Board",
        "side_window" to "Side Window",
        "sidemirror" to "Side Mirror",
        "tail_light_min" to "Tail Light (Minor)",
        "tail_light_mod" to "Tail Light (Moderate)",
        "tail_light_sev" to "Tail Light (Severe)",
        "trunk_min" to "Trunk (Minor)",
        "trunk_mod" to "Trunk (Moderate)",
        "trunk_sev" to "Trunk (Severe)"
    )
}
